@WidgetCo.Store.Api_HostAddress = https://localhost:7169

GET {{WidgetCo.Store.Api_HostAddress}}/api/products

###

POST {{WidgetCo.Store.Api_HostAddress}}/api/products
Content-Type: application/json

{
  //CreateProductRequest
}

###

GET {{WidgetCo.Store.Api_HostAddress}}/api/products/string

###

PUT {{WidgetCo.Store.Api_HostAddress}}/api/products/string
Content-Type: application/json

{
  //UpdateProductRequest
}

###
