name: Deploy Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'src/Functions/**'
      - 'src/Core/**'
      - 'src/Infrastructure/**'

env:
  AZURE_FUNCTIONAPP_NAME: widgetco-functions
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './published'
  SOLUTION_FILE_PATH: './src'
  PROJECT_PATH: './src/Functions/Functions.csproj'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE_PATH }}

    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}